use schema TECH;

CREATE OR REPLACE NETWORK RULE TECH.F1_API_NETWORK_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('api.openf1.org');

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION F1_API_INTEGRATION
ALLOWED_NETWORK_RULES = (F1_API_NETWORK_RULE)
ENABLED = TRUE;

GRANT USAGE ON INTEGRATION F1_API_INTEGRATION TO ROLE F1_CICD_ROLE;

USE ROLE F1_CICD_ROLE;
