USE ROLE ACCOUNTADMIN;

-- This role will be used to perform transformations.
CREATE ROLE IF NOT EXISTS F1_TRANSFORM
    COMMENT = 'Role used for transforming F1 data';


-- create a specific warehouse for transformation to isolate compute costs.
CREATE WAREHOUSE IF NOT EXISTS F1_TRANSFORM_WH
    WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for transformation workloads';


-- The role needs usage to run queries and operate to resume the warehouse.
GRANT USAGE ON WAREHOUSE F1_TRANSFORM_WH TO ROLE F1_TRANSFORM;
GRANT OPERATE ON WAREHOUSE F1_TRANSFORM_WH TO ROLE F1_TRANSFORM;

GRANT USAGE ON DATABASE F1 TO ROLE F1_TRANSFORM;

GRANT USAGE ON SCHEMA F1.RAW TO ROLE F1_TRANSFORM;

GRANT SELECT ON ALL TABLES IN SCHEMA F1.RAW TO ROLE F1_TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA F1.RAW TO ROLE F1_TRANSFORM;

GRANT ROLE F1_TRANSFORM TO ROLE SYSADMIN;
