CREATE OR REPLACE WAREHOUSE F1_WH
  WITH WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;
  
CREATE DATABASE F1;


CREATE OR REPLACE NETWORK RULE F1_API_NETWORK_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('api.openf1.org');


CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION F1_API_INTEGRATION
ALLOWED_NETWORK_RULES = (F1_API_NETWORK_RULE)
ENABLED = TRUE;

GRANT USAGE ON INTEGRATION F1_API_INTEGRATION TO ROLE ACCOUNTADMIN;

CREATE SCHEMA RAW;
